[project]
name = "budget"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "django",
    "django-extensions>=4.1",
    "djangorestframework",
    "drf-spectacular",
    "pre-commit>=4.5.1",
    "psycopg[binary]",
<<<<<<< HEAD
    "Pillow",
=======
    "ruff>=0.14.10",
>>>>>>> 4affc15 (Resolve conflicts after rebase)
]

[dependency-groups]
dev = [
    "ruff",
    "python-dotenv",
    "pre-commit",
]
prod = [
    "gunicorn",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501", "F403"]
